/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Talent Service
 * talent APIs
 * OpenAPI spec version: 1.0
 */

export interface EngineerSignUpInput {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  birthday?: Date;
  frontIdentification?: Blob;
  backIdentification?: Blob;
}
