/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Talent Service
 * talent APIs
 * OpenAPI spec version: 1.0
 */

export interface SupporterSignInInput {
  email: string;
  password: string;
}
