/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { CompanySignUpValidationError } from "./companySignUpValidationError";

export interface CompanySignUpResponse {
  errors: CompanySignUpValidationError;
}
