/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { CompanyMember } from "./companyMember";
import type { CompanyMemberUpdateValidationError } from "./companyMemberUpdateValidationError";

export interface CompanyMemberUpdateResponse {
  companyMember: CompanyMember;
  errors: CompanyMemberUpdateValidationError;
}
