/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { Company } from "./company";
import type { CompanyUpdateValidationError } from "./companyUpdateValidationError";

export interface CompanyUpdateResponse {
  company: Company;
  errors: CompanyUpdateValidationError;
}
