/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { CompanyProduct } from "./companyProduct";
import type { CompanyProductUpdateValidationError } from "./companyProductUpdateValidationError";

export interface CompanyProductUpdateResponse {
  companyProduct: CompanyProduct;
  errors: CompanyProductUpdateValidationError;
}
