/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { CompanyStory } from "./companyStory";
import type { CompanyStoryUpdateValidationError } from "./companyStoryUpdateValidationError";

export interface CompanyStoryUpdateResponse {
  companyStory: CompanyStory;
  errors: CompanyStoryUpdateValidationError;
}
