/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */

export interface CompanyStoryUpdateValidationError {
  mission?: string[];
  vision?: string[];
}
