/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */

export interface ProfileUpdateInput {
  name: string;
  logo?: Blob;
  email: string;
  address?: string;
  siteUrl?: string;
  employeeCount?: number;
  industryId?: number;
}
