/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Business Service
 * business APIs
 * OpenAPI spec version: 1.0
 */
import type { TechBlog } from "./techBlog";
import type { TechBlogUpdateValidationError } from "./techBlogUpdateValidationError";

export interface TechBlogUpdateResponse {
  techBlog: TechBlog;
  errors: TechBlogUpdateValidationError;
}
