version: "3.9"
services:
  api_server:
    container_name: api_server
    build:
      context: ./api-server
      dockerfile: Dockerfile.dev
    volumes:
      - ./api-server:/app
    ports:
      - 4000:4000
    depends_on:
      - db
    tty: true # コンテナの永続化
    environment:
      - TZ=Asia/Tokyo

  db:
    image: mysql:8.0.36
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: engineer_business_matching
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql

  gcs:
    image: fsouza/fake-gcs-server
    tty: true
    ports:
      - 4443:4443
    volumes:
      - ./.data:/data/engineer_business_matching_dev
      - ./.storage:/storage
    command: -scheme http -public-host ${URL:-localhost}:4443 -external-url http://${URL:-gcs}:4443 -port-http 8000
