openapi: 3.1.0
info:
  title: Talent Service
  version: '1.0'
  description: talent APIs
tags:
  - name: supporters
paths:
  /supporters/sign-in:
    post:
      operationId: post-supporter-sign-in
      summary: Supporter Sign In
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignInOkResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignInBadRequestResponse'
        '500':
          description: Server error
      tags:
        - supporters
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SupporterSignInInput'
  /supporters/sign-up:
    post:
      operationId: post-supporter-sign-up
      summary: Supporter Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '500':
          description: Server error
      tags:
        - supporters
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupporterSignUpInput'
  /supporters/validate-sign-up:
    post:
      operationId: post-supporter-validate-sign-up
      summary: Supporter Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupporterSignUpResponse'
        '500':
          description: Server error
      tags:
        - supporters
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SupporterSignUpInput'
components:
  schemas:
    SupporterSignInBadRequestResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: string
      title: Supporter SignIn BadRequestError Response
    SupporterSignInInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      title: Supporter SignIn Input
    SupporterSignInOkResponse:
      type: object
      required:
        - token
      properties:
        token:
          type: string
      title: Supporter SignIn Ok Response
    SupporterSignUpInput:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        frontIdentification:
          type: string
          format: binary
        backIdentification:
          type: string
          format: binary
      required:
        - firstName
        - lastName
        - email
        - password
    SupporterSignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/SupporterSignUpValidationError'
      title: Supporter SignUp Response
    SupporterSignUpValidationError:
      type: object
      properties:
        firstName:
          type: array
          items:
            type: string
        lastName:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        birthday:
          type: array
          items:
            type: string
        frontIdentification:
          type: array
          items:
            type: string
        backIdentification:
          type: array
          items:
            type: string
      title: Supporter SignUp Validation Error
servers:
  - url: https://localhost:4000
    variables: {}
