openapi: 3.1.0
info:
  title: Talent Service
  version: '1.0'
  description: talent APIs
tags:
  - name: engineers
  - name: profile
paths:
  /engineers/sign-in:
    post:
      operationId: post-engineer-sign-in
      summary: Engineer Sign In
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignInResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignInResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EngineerSignInInput'
  /engineers/sign-up:
    post:
      operationId: post-engineer-sign-up
      summary: Engineer Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EngineerSignUpInput'
  /engineers/validate-sign-up:
    post:
      operationId: post-engineer-validate-sign-up
      summary: Engineer Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EngineerSignUpInput'
  /profile:
    get:
      operationId: get-profile
      summary: Show Profile
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - profile
      security:
        - TalentBearerAuth: []
    put:
      operationId: put-profile
      summary: Update profile
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdateResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdateResponse'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateInput'
      security:
        - TalentBearerAuth: []
components:
  schemas:
    EngineerSignInInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      title: Engineer SignIn Input
    EngineerSignInResponse:
      type: object
      required:
        - token
        - error
      properties:
        token:
          type: string
        error:
          type: string
      title: Engineer SignIn Response
    EngineerSignUpInput:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        frontIdentification:
          type: string
          format: binary
        backIdentification:
          type: string
          format: binary
      required:
        - firstName
        - lastName
        - email
        - password
    EngineerSignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/EngineerSignUpValidationError'
      title: Engineer SignUp Response
    EngineerSignUpValidationError:
      type: object
      properties:
        firstName:
          type: array
          items:
            type: string
        lastName:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        birthday:
          type: array
          items:
            type: string
        frontIdentification:
          type: array
          items:
            type: string
        backIdentification:
          type: array
          items:
            type: string
      title: Engineer SignUp Validation Error
    Profile:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthday:
          type: string
          format: date
        address:
          type: string
        currentEmployer:
          type: string
        tel:
          type: string
      title: Profile
    ProfileUpdateInput:
      type: object
      required:
        - firstName
        - lastName
      properties:
        firstName:
          type: string
        lastName:
          type: string
        birthday:
          type: string
          format: date
        address:
          type: string
        currentEmployer:
          type: string
        tel:
          type: string
      title: Profile
    ProfileUpdateResponse:
      type: object
      required:
        - profile
        - errors
      properties:
        profile:
          $ref: '#/components/schemas/Profile'
        errors:
          $ref: '#/components/schemas/ProfileUpdateValidationError'
      title: Profile Update Response
    ProfileUpdateValidationError:
      type: object
      properties:
        firstName:
          type: array
          items:
            type: string
        lastName:
          type: array
          items:
            type: string
        birthday:
          type: array
          items:
            type: string
        address:
          type: array
          items:
            type: string
        currentEmployer:
          type: array
          items:
            type: string
        tel:
          type: array
          items:
            type: string
      title: Profile Update Validation Error
  securitySchemes:
    TalentBearerAuth:
      type: apiKey
      in: header
      name: Talent-Authorization
servers:
  - url: https://localhost:4000
    variables: {}
