openapi: 3.1.0
info:
  title: Talent Service
  version: '1.0'
  description: talent APIs
tags:
  - name: engineers
paths:
  /engineers/sign-in:
    post:
      operationId: post-engineer-sign-in
      summary: Engineer Sign In
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignInResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignInResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EngineerSignInInput'
  /engineers/sign-up:
    post:
      operationId: post-engineer-sign-up
      summary: Engineer Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EngineerSignUpInput'
  /engineers/validate-sign-up:
    post:
      operationId: post-engineer-validate-sign-up
      summary: Engineer Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EngineerSignUpResponse'
        '500':
          description: Server error
      tags:
        - engineers
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/EngineerSignUpInput'
components:
  schemas:
    EngineerSignInInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      title: Engineer SignIn Input
    EngineerSignInResponse:
      type: object
      required:
        - token
        - error
      properties:
        token:
          type: string
        error:
          type: string
      title: Engineer SignIn Response
    EngineerSignUpInput:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        birthday:
          type: string
          format: date
        frontIdentification:
          type: string
          format: binary
        backIdentification:
          type: string
          format: binary
      required:
        - firstName
        - lastName
        - email
        - password
    EngineerSignUpResponse:
      type: object
      required:
        - code
        - errors
      properties:
        code:
          type: integer
        errors:
          $ref: '#/components/schemas/EngineerSignUpValidationError'
      title: Engineer SignUp Response
    EngineerSignUpValidationError:
      type: object
      properties:
        firstName:
          type: array
          items:
            type: string
        lastName:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        birthday:
          type: array
          items:
            type: string
        frontIdentification:
          type: array
          items:
            type: string
        backIdentification:
          type: array
          items:
            type: string
      title: Engineer SignUp Validation Error
servers:
  - url: https://localhost:4000
    variables: {}
