openapi: 3.1.0
info:
  title: Business Service
  version: '1.0'
  description: business APIs
tags:
  - name: companies
  - name: CompanyStory
  - name: csrf
  - name: profile
paths:
  /companies/sign-in:
    post:
      operationId: post-company-sign-in
      summary: Company Sign In
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          headers:
            Set-Cookie:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignInResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignInResponse'
        '500':
          description: Server error
      tags:
        - companies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanySignInInput'
  /companies/sign-up:
    post:
      operationId: post-company-sign-up
      summary: Company Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
  /companies/validate-sign-up:
    post:
      operationId: post-company-validate-sign-up
      summary: Company Validate Sign Up
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanySignUpResponse'
        '500':
          description: Server error
      tags:
        - companies
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CompanySignUpInput'
  /company-stories:
    get:
      operationId: get-company-story
      summary: Show CompanyStory
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyStory'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - CompanyStory
      security:
        - BusinessBearerAuth: []
    put:
      operationId: put-company-story
      summary: Update CompanyStory
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyStoryUpdateResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyStoryUpdateResponse'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - CompanyStory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompanyStoryUpdateInput'
      security:
        - BusinessBearerAuth: []
  /csrf:
    get:
      operationId: get-csrf
      summary: Get Csrf
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CsrfResponse'
        '500':
          description: Server error
      tags:
        - csrf
  /profile:
    get:
      operationId: get-profile
      summary: Show Profile
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - profile
      security:
        - BusinessBearerAuth: []
    put:
      operationId: put-profile
      summary: Update profile
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdateResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileUpdateResponse'
        '404':
          description: The server cannot find the requested resource.
        '500':
          description: Server error
      tags:
        - profile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProfileUpdateInput'
      security:
        - BusinessBearerAuth: []
components:
  schemas:
    CompanySignInInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      title: Company SignIn Input
    CompanySignInResponse:
      type: object
      required:
        - token
        - error
      properties:
        token:
          type: string
        error:
          type: string
      title: Company SignIn Response
    CompanySignUpInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        finalTaxReturn:
          type: string
          format: binary
      required:
        - name
        - email
        - password
    CompanySignUpResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          $ref: '#/components/schemas/CompanySignUpValidationError'
      title: Company SignUp Response
    CompanySignUpValidationError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        password:
          type: array
          items:
            type: string
        finalTaxReturn:
          type: array
          items:
            type: string
      title: Company SignUp Validation Error
    CompanyStory:
      type: object
      required:
        - mission
        - vision
      properties:
        mission:
          type: string
        vision:
          type: string
      title: CompanyStory
    CompanyStoryUpdateInput:
      type: object
      required:
        - mission
        - vision
      properties:
        mission:
          type: string
        vision:
          type: string
      title: CompanyStoryUpdateInput
    CompanyStoryUpdateResponse:
      type: object
      required:
        - companyStory
        - errors
      properties:
        companyStory:
          $ref: '#/components/schemas/CompanyStory'
        errors:
          $ref: '#/components/schemas/CompanyStoryUpdateValidationError'
      title: CompanyStory Update Response
    CompanyStoryUpdateValidationError:
      type: object
      properties:
        mission:
          type: array
          items:
            type: string
        vision:
          type: array
          items:
            type: string
      title: CompanyStory Update Validation Error
    CsrfResponse:
      type: object
      required:
        - csrfToken
      properties:
        csrfToken:
          type: string
      title: CsrfResponse
    Profile:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        logoUrl:
          type: string
        email:
          type: string
        address:
          type: string
        siteUrl:
          type: string
        employeeCount:
          type: integer
        industryId:
          type: integer
      title: Profile
    ProfileUpdateInput:
      type: object
      properties:
        name:
          type: string
        logo:
          type: string
          format: binary
        email:
          type: string
        address:
          type: string
        siteUrl:
          type: string
        employeeCount:
          type: integer
        industryId:
          type: integer
      required:
        - name
        - email
    ProfileUpdateResponse:
      type: object
      required:
        - profile
        - errors
      properties:
        profile:
          $ref: '#/components/schemas/Profile'
        errors:
          $ref: '#/components/schemas/ProfileUpdateValidationError'
      title: Profile Update Response
    ProfileUpdateValidationError:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        logo:
          type: array
          items:
            type: string
        email:
          type: array
          items:
            type: string
        address:
          type: array
          items:
            type: string
        siteUrl:
          type: array
          items:
            type: string
        employeeCount:
          type: array
          items:
            type: string
        industryId:
          type: array
          items:
            type: string
      title: Profile Update Validation Error
  securitySchemes:
    BusinessBearerAuth:
      type: apiKey
      in: header
      name: Business-Authorization
servers:
  - url: https://localhost:4000
    variables: {}
