import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BaseContainer from "@repo/ui/BaseContainer/index";
import TanstackQueryProvider from "@/lib/tanstackQueryProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanstackQueryProvider>
      <html>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="p-4 md:p-16">
            <BaseContainer containerWidth="w-4/5">{children}</BaseContainer>
          </div>
        </body>
      </html>
    </TanstackQueryProvider>
  );
}
