name: E2E

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.36
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: engineer_business_matching_test
          TZ: "Asia/Tokyo"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Rubyのセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          ruby-version: 3.4
          bundler-cache: true

      # 必要なGemのインストール
      - name: Install dependencies
        working-directory: api-server
        run: bundle install

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@7bc0b195ea4bef7a215f1ec0f71e41fedc6f0e15 # v0.2.2
        with:
          install-awslocal: "true"

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id dummy
          aws configure set aws_secret_access_key dummy
          aws configure set region ap-northeast-1

      - name: Make Test Bucket on LocalStack
        run: |
          awslocal s3 mb s3://engineer-business-matching-test

      - name: Boot API Server
        working-directory: ./api-server
        run: |
          rm -f tmp/pids/server.pid
          bundle exec rails s -e test -p 4100 -b '0.0.0.0' &

      - name: migrate
        working-directory: ./api-server
        run: RAILS_ENV=test rails ridgepole:apply

      # - name: Seeding
      #   working-directory: ./api-server
      #   run: make test-seed-ci

      - uses: awalsh128/cache-apt-pkgs-action@4c82c3ccdc1344ee11e9775dbdbdf43aa8a5614e # v1.5.1
        with:
          packages: language-pack-ja fontconfig fonts-ipafont
          version: 1.0

      - name: Verify Japanese fonts
        run: |
          fc-list :lang=ja

      - name: Set Japanese locale
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
          export LANG=ja_JP.UTF-8

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 9

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          VERSION=$(yq '.importers.".".devDependencies."@playwright/test".version' frontend/pnpm-lock.yaml)
          echo "PLAYWRIGHT_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Cache playwright binaries
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm i

      - run: pnpm playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: ./frontend

      - name: Run Playwright tests
        working-directory: ./frontend
        run: pnpm test:e2e

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: business-e2e-test-results
          path: ./frontend/apps/business/test-results/
          retention-days: 30

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ !cancelled() }}
        with:
          name: talent-e2e-test-results
          path: ./frontend/apps/talent/test-results/
          retention-days: 30
